### ISSUE TITLE
Exception during execution

### ISSUE THREAD

**Issue by viniciusbarbosa** [acesinc/json-data-generator#15]
Hello! 
Congratulations on your code, it is helping me a lot!

I'm trying to connect the kafka and the data-stream, but it has not worked.
The zookeeper and Kafka are ok, I have a topic, consumer and producer.
Always get this error displayed below.
Can you help me please?

`root@vinicius-vm-3:/home/vinicius/json-data-generator/files# java -jar json-data-generator-1.2.2-SNAPSHOT.jar producer.json
2016-10-06 15:27:01,636 INFO n.a.d.j.g.JsonDataGenerator [main] Overriding Simulation Config file from command line to use [ producer.json ]
2016-10-06 15:27:01,643 DEBUG n.a.d.j.g.JsonDataGenerator [main] Creating Simulation Runner using Simulation Config [ producer.json ]
2016-10-06 15:27:01,965 INFO n.a.d.j.g.JsonDataGenerator [main] Adding Kafka Producer with properties: {type=kafka, broker.server=127.0.0.1, broker.port=9092, topic=topico-json-data, sync=false}
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NullPointerException
    at net.acesinc.data.json.generator.log.KafkaLogger.<init>(KafkaLogger.java:49)
    at net.acesinc.data.json.generator.JsonDataGenerator.<init>(JsonDataGenerator.java:51)
    at net.acesinc.data.json.generator.JsonDataGenerator.main(JsonDataGenerator.java:107)
root@vinicius-vm-3:/home/vinicius/json-data-generator/files# 
`

Thanks
Sorry my english

**Comment by andrewserff** [comment]
Sorry for the delay in responding, I missed this issue!  It looks like you don't have the `flatten` property set in your config.  Can you set that to `false` (I assume since you don't already have it) and see if that fixes the issue?  I'll add a check to see if that's not set and default it to false in the future.

**Comment by andrewserff** [comment]
I just commited a check to stop that NPE you were getting.  so either try to pull a new baseline, or set `flatten` to false.

**Comment by andrewserff** [comment]
Closing based on lack of activity. If there is still an issue, please let me know.
