### ISSUE TITLE
Question regarding one work floww to one producer 

### ISSUE THREAD

**Issue by sriharshamutnuru** [acesinc/json-data-generator#17]
how to link one work flow to one producer  but not all producers like it's happening  currently .

**Comment by andrewserff** [comment]
If I understand correctly, there isn't a way to do this currently.  You would just need to make separate simulation configs with only one producer.

**Comment by sriharshamutnuru** [comment]
Thanks Andrew,as you said to make separate configs,how can we do multiple config files that and how we run those multiple config files

**Comment by andrewserff** [comment]
Just pass the name of the config when you start it. If you need them running at the same time, you would have to run separate instances of the generator, passing different configs to each one.

**Comment by sriharshamutnuru** [comment]
i have changed the sim config file like this and changed the code  to run the multiple workflows to multiple producers  simultaneously 
{
    "workflows": [{
    "workflowName": "Harsha",
    "workflowFilename": "newWorkflow2.json",
    "producers": [{
     "type": "logger"
    }]
  },
  {
    "workflowName": "Harsha",
    "workflowFilename": "newWorkflow.json",
    "producers": [{
     "type": "logger"
    }]
  }]
}

**Comment by sriharshamutnuru** [comment]
after running generator,  records randomly  generated for some time suddenly one of the threads stopping by the exception 


org.apache.commons.math3.exception.NumberIsTooLargeException: lower bound (0) must be strictly less than upper bound (-1)
	at org.apache.commons.math3.distribution.UniformIntegerDistribution.<init>(UniformIntegerDistribution.java:78) ~[commons-math3-3.5.jar:3.5]
	at org.apache.commons.math3.random.RandomDataGenerator.nextInt(RandomDataGenerator.java:198) ~[commons-math3-3.5.jar:3.5]
	at net.acesinc.data.json.generator.types.RandomType.getNextRandomValue(RandomType.java:47) ~[classes/:?]
	at net.acesinc.data.json.generator.RandomJsonGenerator.processProperties(RandomJsonGenerator.java:102) [classes/:?]
	at net.acesinc.data.json.generator.RandomJsonGenerator.processProperties(RandomJsonGenerator.java:134) [classes/:?]
	at net.acesinc.data.json.generator.RandomJsonGenerator.generateJson(RandomJsonGenerator.java:50) [classes/:?]
	at net.acesinc.data.json.generator.EventGenerator.generateEvent(EventGenerator.java:258) [classes/:?]
	at net.acesinc.data.json.generator.EventGenerator.executeStep(EventGenerator.java:129) [classes/:?]
	at net.acesinc.data.json.generator.EventGenerator.runRandom(EventGenerator.java:88) [classes/:?]
	at net.acesinc.data.json.generator.EventGenerator.runWorkflow(EventGenerator.java:50) [classes/:?]
	at net.acesinc.data.json.generator.EventGenerator.run(EventGenerator.java:339) [classes/:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]

**Comment by sriharshamutnuru** [comment]
some times generator not able to pick the random value from the json and getting null pointer exception too

**Comment by andrewserff** [comment]
Your sim config is invalid.  You can only have one in the file (needs to be valid json). Put them in two separate files (simConfig1.json, simConfig2.json). As for the exceptions, I guess I'd need to see the workflow configs.  I've never seen that happen.  Are you passing a very large number into an `integer()` in your conifg as a max value? and what is the NPE you are seeing?

**Comment by sriharshamutnuru** [comment]
[workflow.txt](https://github.com/acesinc/json-data-generator/files/625307/workflow.txt)


this is the work flow iam using

**Comment by sriharshamutnuru** [comment]
Iam getting NPE for the any one of the keys in the workflow not one specifically

**Comment by drakulavich** [comment]
@sriharshamutnuru Please, check out the new version. I've fixed issues like this:
```
org.apache.commons.math3.exception.NumberIsTooLargeException: lower bound (0) must be strictly less than upper bound (-1)
```

**Comment by andrewserff** [comment]
Closing based on lack of activity. If there is still an issue, please let me know.
