### ISSUE TITLE
Error in double() function

### ISSUE THREAD

**Issue by gonzalobd** [acesinc/json-data-generator#18]
Hi!

Running your jackieChan example sedngin it to kafka it returns next exception:

`2016-12-06 18:42:33,202 WARN n.a.d.j.g.RandomJsonGenerator [Thread-2] Error creating type [ double(1.0,10.0) ]. Prop [ strength ] being ignored in output.  Reason: For input string: "4,3396"
2016-12-06 18:42:33,202 DEBUG n.a.d.j.g.RandomJsonGenerator [Thread-2] Error creating type [ double(1.0,10.0) ]. Prop [ strength ] being ignored in output.
java.lang.NumberFormatException: For input string: "4,3396"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:1.8.0_111]
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_111]
	at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_111]
`

and the strenght value is ignored in output:

`2016-12-06 18:42:33,219 DEBUG n.a.d.j.g.l.KafkaLogger [Thread-2] Sending event to Kafka: [ {"timestamp":"2016-12-06T18:42:33.163Z","style":"KUNG_FU","action":"JUMP","weapon":"ROPE","target":"HEAD"} ]
`

Thanks!

**Comment by drakulavich** [comment]
Hi @gonzalobd! 

I've prepared fix in PR #23. Check it out.

**Comment by andrewserff** [comment]
Closing based on lack of activity. If there is still an issue, please let me know.
