### ISSUE TITLE
RandomType is thread unsafe

### ISSUE THREAD

**Issue by drakulavich** [acesinc/json-data-generator#19]
Hi there!
Thanks a lot for the great tool!

I've changed exampleSimConfig.json to check JSON generating with multiple threads:
```
{
    "workflows": [{
            "workflowName": "test",
            "workflowFilename": "exampleWorkflow.json"
        }, {
            "workflowName": "test",
            "workflowFilename": "exampleWorkflow.json"
        },
        {
            "workflowName": "test",
            "workflowFilename": "exampleWorkflow.json"
        }
    ],
    "producers": [{
            "type": "logger"
        },
        {
            "type": "file",
            "output.directory": "test_data/test",
            "file.prefix": "test_",
            "file.extension": ".json"
        }
    ]
}
```
I've got many errors during simulation:
```
DEBUG n.a.d.j.g.RandomJsonGenerator [Thread-2] Error creating type [ random("PRINT","OPEN","COPY") ]. Prop [ action ] being ignored in output.
org.apache.commons.math3.exception.NumberIsTooLargeException: lower bound (0) must be strictly less than upper bound (-1)
	at org.apache.commons.math3.distribution.UniformIntegerDistribution.<init>(UniformIntegerDistribution.java:78) ~[commons-math3-3.5.jar:3.5]
	at org.apache.commons.math3.random.RandomDataGenerator.nextInt(RandomDataGenerator.java:198) ~[commons-math3-3.5.jar:3.5]
	at net.acesinc.data.json.generator.types.RandomType.getNextRandomValue(RandomType.java:48) ~[json-data-generator-1.2.2-SNAPSHOT.jar:1.2.2-SNAPSHOT]
	at net.acesinc.data.json.generator.RandomJsonGenerator.processProperties(RandomJsonGenerator.java:102) [json-data-generator-1.2.2-SNAPSHOT.jar:1.2.2-SNAPSHOT]
	at net.acesinc.data.json.generator.RandomJsonGenerator.processProperties(RandomJsonGenerator.java:133) [json-data-generator-1.2.2-SNAPSHOT.jar:1.2.2-SNAPSHOT]
	at net.acesinc.data.json.generator.RandomJsonGenerator.generateJson(RandomJsonGenerator.java:50) [json-data-generator-1.2.2-SNAPSHOT.jar:1.2.2-SNAPSHOT]
	at net.acesinc.data.json.generator.EventGenerator.generateEvent(EventGenerator.java:243) [json-data-generator-1.2.2-SNAPSHOT.jar:1.2.2-SNAPSHOT]
	at net.acesinc.data.json.generator.EventGenerator.executeStep(EventGenerator.java:182) [json-data-generator-1.2.2-SNAPSHOT.jar:1.2.2-SNAPSHOT]
	at net.acesinc.data.json.generator.EventGenerator.runSequential(EventGenerator.java:71) [json-data-generator-1.2.2-SNAPSHOT.jar:1.2.2-SNAPSHOT]
	at net.acesinc.data.json.generator.EventGenerator.runWorkflow(EventGenerator.java:53) [json-data-generator-1.2.2-SNAPSHOT.jar:1.2.2-SNAPSHOT]
	at net.acesinc.data.json.generator.EventGenerator.run(EventGenerator.java:257) [json-data-generator-1.2.2-SNAPSHOT.jar:1.2.2-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

I would appreciate any suggestion to solve this issue.

**Comment by drakulavich** [comment]
ThreadLocal TypeHandlerFactory from #22 fixes the issue above.
