### ISSUE TITLE
Error in providing sim config file

### ISSUE THREAD

**Issue by ahmedulde** [acesinc/json-data-generator#24]
If i provide the sim config as specified in documentation, i get the error below.

<code>
$ java -jar json-data-generator-1.2.2-SNAPSHOT.jar conf\exampleSimConfig.json
2017-03-12 14:38:38,462 INFO n.a.d.j.g.JsonDataGenerator [main] Overriding Simulation Config file from command line to use [ conf\exampleSimConfig.json ]
2017-03-12 14:38:38,466 DEBUG n.a.d.j.g.JsonDataGenerator [main] Creating Simulation Runner using Simulation Config [ conf\exampleSimConfig.json ]
2017-03-12 14:38:38,681 ERROR n.a.d.j.g.JsonDataGenerator [main] Error getting Simulation Config [ conf\exampleSimConfig.json ]
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: UNKNOWN; line: 1, column: 1]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148) ~[jackson-databind-2.5.2.jar:2.5.2]
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3607) ~[jackson-databind-2.5.2.jar:2.5.2]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3547) ~[jackson-databind-2.5.2.jar:2.5.2]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2648) ~[jackson-databind-2.5.2.jar:2.5.2]
        at net.acesinc.data.json.generator.config.JSONConfigReader.readConfig(JSONConfigReader.java:42) ~[json-data-generator-1.2.2-SNAPSHOT.jar:1.2.2-SNAPSHOT]
        at net.acesinc.data.json.generator.JsonDataGenerator.getSimConfig(JsonDataGenerator.java:103) ~[json-data-generator-1.2.2-SNAPSHOT.jar:1.2.2-SNAPSHOT]
        at net.acesinc.data.json.generator.JsonDataGenerator.<init>(JsonDataGenerator.java:35) [json-data-generator-1.2.2-SNAPSHOT.jar:1.2.2-SNAPSHOT]
        at net.acesinc.data.json.generator.JsonDataGenerator.main(JsonDataGenerator.java:117) [json-data-generator-1.2.2-SNAPSHOT.jar:1.2.2-SNAPSHOT]
Exception in thread "main" java.lang.NullPointerException
        at net.acesinc.data.json.generator.JsonDataGenerator.startRunning(JsonDataGenerator.java:95)
        at net.acesinc.data.json.generator.JsonDataGenerator.main(JsonDataGenerator.java:132)
2017-03-12 14:38:38,693 INFO n.a.d.j.g.JsonDataGenerator [Thread-1] Shutdown Hook Invoked.  Shutting Down Loggers
Exception in thread "Thread-1" java.lang.NullPointerException
        at net.acesinc.data.json.generator.JsonDataGenerator.stopRunning(JsonDataGenerator.java:99)
        at net.acesinc.data.json.generator.JsonDataGenerator$1.run(JsonDataGenerator.java:123)
</code>

When i looked into the source code looks like the sim config is read as stream so i used the command below and i was able to see the generator working.

<code>
java -jar json-data-generator-1.2.2-SNAPSHOT.jar | cat conf\exampleSimConfig.json
</code>

I am using windows to run this generator. Let me know if this is a valid issue or not.

**Comment by andrewserff** [comment]
Did you change the exampleSimConfig.json? It looks to me like that file is invalid. You could post the file here if you need help fixing it.

**Comment by ahmedulde** [comment]
I am using the default file which i get after compiling the source and extracting tar

**Comment by hmajumdar** [comment]
I am getting the same error with the default file itself tried `java -jar json-data-generator-1.0.0.jar exampleSimConfig.json` and `java -jar json-data-generator-1.2.2-SNAPSHOT.jar "conf/exampleSimConfig.json"`

**Comment by andrewserff** [comment]
@ahmedulde can you try removing `conf` from your command? So run:
`java -jar json-data-generator-1.2.2-SNAPSHOT.jar exampleSimConfig.json`

This is working for me.  We should be throwing a `FileNotFoundException` if we can't load it instead of what is happening right now.  

@hmajumdar I'm not sure why yours wouldn't work unless it's because you have `json-data-generator-1.0.0.jar` instead of `1.2.2-SNAPSHOT` (or what ever version you are running. Can you double check it doesn't work like above?

**Comment by hmajumdar** [comment]
@andrewserff I copied simConfig files into parent directly like this to make it work. 

<img width="447" alt="screen shot 2017-03-14 at 1 37 32 pm" src="https://cloud.githubusercontent.com/assets/4563760/23914157/7c56e144-08bb-11e7-8671-2b2b0836640f.png">

**Comment by ahmedulde** [comment]
`java -jar json-data-generator-1.2.2-SNAPSHOT.jar | cat conf\exampleSimConfig.json `

Above command works well. Tried removing conf didnt work.

**Comment by andrewserff** [comment]
@ahmedulde If the logging is set to TRACE for the `EventGenerator` you should be seeing log messages like: 
`2017-03-14 14:14:24,892 TRACE n.a.d.j.g.EventGenerator [Thread-1] Generator( my-random ) generated 3.0 events/sec`

The exampleSimConfig generate things very slowly so it doesn't get much per second. Hopefully that's what you're after.

**Comment by andrewserff** [comment]
Closing based on lack of activity. If there is still an issue, please let me know.
